version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    container_name: h2h-server
    networks:
      - h2h-app
    depends_on:
      - mongo
    env_file:
      - ./.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/h2h

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # volumes:
    #   - /media/grio/tutorials/githubclone/H2H-Real-Time-Chat-App/client:/app
    #   - /media/grio/tutorials/githubclone/H2H-Real-Time-Chat-App/client/app/node_modules
    container_name: h2h-client
    networks:
      - h2h-app
    depends_on:
      - server

  mongo:
    image: mongo:latest
    ports:
      - "9000:27017"
    container_name: h2h-db
    networks:
      - h2h-app
    volumes:
      - mongo-data:/data/db

networks:
  h2h-app:
    driver: bridge

volumes:
  mongo-data:
# Note:
# docker-compose up -d --build
# docker logs container-name
# Verify Docker ENV
# docker exec -it h2h-server /bin/bash
# printenv | grep PORT

